# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 265b38060214eddc071c3013b46cef4b7ffbfc5b6ec8eb296298175b8ece74a2690dff3f6db0768c33f3935b2f68166a35fe5731bf70c0ff0aff081bb0d3e2a3

test:
  secret_key_base: 27643303f84297f30f95fa50e3ec267691930b5caa888fdf2d82810cc9451ebe58079d878719a3b08b1a21a1fb3bc46885985488c23dcf5deeb81bf7926981bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
